# GM v Linear

## Load packages + data
```{r load.gmlin, echo=TRUE, warning=FALSE}
# download most recent software version
#devtools::install_github("geomorphR/geomorph", ref = "Stable", build_vignettes = TRUE)
#devtools::install_github("mlcollyer/RRPP")

# load analysis packages
library(here)
library(StereoMorph)
library(geomorph)
library(ggplot2)
library(dplyr)
library(wesanderson)

# read shape data and define number of sLMs
shapes <- readShapes("shapes")
shapesGM <- readland.shapes(shapes, 
                            nCurvePts = c(10,3,5,5,3,10))

# read qualitative data
qdata <- read.csv("qdata.morph.csv",
                  header = TRUE,
                  row.names = 1)
```

## Generalised Procrustes Analysis

```{r gpagmlin, echo=TRUE, out.width = "100%", dpi = 300, warning=FALSE}
# gpa
Y.gpa <- gpagen(shapesGM, print.progress = FALSE)

## plot
plot(Y.gpa)

# dataframe
gdf <- geomorph.data.frame(shape = Y.gpa$coords,
                           size = Y.gpa$Csize)
```

## Shape vs linear data (shape vars)

```{r linear.shape, echo=TRUE, out.width = "100%", dpi = 300, warning=FALSE}
# are shape and linear data correlated?
# subset linear data
linear <- qdata %>%
  select(sh.maxbl, sh.maxw, sh.maxshw, sh.maxth, sh.maxstl, sh.maxstw)

# 2B-PLS
shape.meas.cor <- two.b.pls(A1 = Y.gpa$coords, 
                            A2 = linear,
                            print.progress = FALSE,
                            iter = 9999)
summary(shape.meas.cor)

## plot PLS
plot(shape.meas.cor)
```

## Shape vs linear data (linear vars)

```{r linear.shape.2, echo=TRUE, out.width = "100%", dpi = 300, warning=FALSE}
# are shape and linear data correlated?
# subset linear data
linear2 <- qdata %>%
  select(maxl, maxw, maxth, maxstl, maxstw)

# 2B-PLS
shape.meas.cor <- two.b.pls(A1 = Y.gpa$coords, 
                            A2 = linear2,
                            print.progress = FALSE,
                            iter = 9999)
summary(shape.meas.cor)

## plot PLS
plot(shape.meas.cor)
```
